import { chromium } from '@playwright/test';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto('http://127.0.0.1:4173/');
await page.waitForLoadState('networkidle');
await page.screenshot({ path: '/tmp/cb_welcome.png' });
await page.getByRole('button', { name: 'Get started' }).click();
await page.waitForTimeout(800);
await page.screenshot({ path: '/tmp/cb_today.png' });
await browser.close();
