import { chromium } from '@playwright/test';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
page.on('console', msg => console.log('PAGE CONSOLE:', msg.type(), msg.text()));
page.on('pageerror', err => console.log('PAGE ERROR:', err.message));
page.on('requestfailed', req => console.log('REQUEST FAILED:', req.url(), req.failure()?.errorText));
await page.goto('http://124.156.206.120/');
await page.waitForTimeout(3000);
await page.screenshot({ path: '/tmp/cb_live_welcome3.png', fullPage: true });
const buttons = await page.locator('button').allInnerTexts();
console.log('BUTTONS:', buttons);
await browser.close();
