import { chromium } from '@playwright/test';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto('http://127.0.0.1:4173/');
await page.waitForTimeout(800);
await page.getByRole('button', { name: 'Get started' }).click();
await page.waitForTimeout(800);
await page.goto('http://127.0.0.1:4173/buddy');
await page.waitForTimeout(800);
await page.locator('#message').fill('What is next today?');
await page.locator('button:has-text("Send")').click();
await page.waitForTimeout(2000);
await page.screenshot({ path: '/tmp/cb_buddy_backend.png' });
const body = await page.content();
console.log(body.includes('routines recorded') ? 'backend response found' : 'no response');
await browser.close();
